#
# .github/workflows/github-release.yml
#
# Copyright 2023 Jens A. Koch.
# SPDX-License-Identifier: MIT
# This file is part of jakoch/wikifolio_universe_converter.
#

name: Draft GitHub Release

on:
  push:
    branches:
      - main
  # You can manually run this workflow.
  workflow_dispatch:

jobs:

# ---------------------------------------------------------------------------------------

  github-release:

# ---------------------------------------------------------------------------------------

    name: Draft GitHub Release
    runs-on: ubuntu-latest
    needs: [build-on-linux, build-on-windows]

    # on tag push
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    env:
      TAG: ${{ github.ref_name }}
      # TODO research, if this is needed?
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 🤘 Checkout Code
        uses: actions/checkout@v3 # https://github.com/actions/checkout

      - name: 🔽 Download all artifacts
        uses: actions/download-artifact@v3 # https://github.com/actions/download-artifact

      - name: Display downloaded files
        run: ls -R

      - name: Extract Release Notes from Changelog
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1 # https://github.com/ffurrer2/extract-release-notes

      - name: 📋 Create Draft Release
        # https://cli.github.com/manual/gh_release_create
        env:
          RELEASE_NOTES: ${{ steps.extract-release-notes.outputs.release_notes }}
        run: |
          gh release create $TAG --title "Release $TAG" --notes "$RELEASE_NOTES" --draft

      #- name: 📦 Create Github Release
      #  # https://cli.github.com/manual/gh_release_upload
      #  run: |
      #    gh release upload $TAG

